#!/usr/bin/env python3
"""
Generate and validate datasets + displayed numbers for the Statistical
Inference section (docs/inference/).

Two datasets, both deterministic (seed 42):

1. Resting heart rate vs weekly exercise hours (Gaussian linear model)
   - used on curvature.html for the 2D log-likelihood surface,
     Hessian -> vcov -> SE pipeline, and the R/Python code panels.
   - n = 200 generated; the page's sample-size slider uses the first n rows.

2. Small-n logistic dataset (treatment response vs biomarker score)
   - used on bayes.html to contrast Wald (quadratic) intervals with
     flat-prior grid-posterior credible intervals.

All numbers quoted in the HTML pages must match this script's output.
Run from scripts/py/:  python3 generate_inference_data.py
"""

import json
import numpy as np
import statsmodels.api as sm
from scipy import stats, optimize

rng = np.random.default_rng(42)

# ---------------------------------------------------------------
# Dataset 1: Gaussian — resting heart rate vs weekly exercise hours
# ---------------------------------------------------------------
N_FULL = 200
DEFAULT_N = 60

exercise = np.round(rng.uniform(0, 10, N_FULL), 1)
noise = rng.normal(0, 6.0, N_FULL)
rest_hr = np.round(75.0 - 1.8 * exercise + noise, 1)

gauss_data = [{"x": float(x), "y": float(y)} for x, y in zip(exercise, rest_hr)]

with open("../../docs/data/inference-rest-hr.json", "w") as f:
    json.dump(
        {
            "description": "Synthetic resting heart rate (bpm) vs weekly exercise hours. "
                           "Generated by scripts/py/generate_inference_data.py, seed 42. "
                           "True values: intercept 75, slope -1.8, sigma 6.",
            "n": N_FULL,
            "data": gauss_data,
        },
        f,
        indent=1,
    )

print("=" * 70)
print("DATASET 1: resting heart rate ~ exercise hours (Gaussian), seed 42")
print("=" * 70)


def gaussian_report(n):
    x = exercise[:n]
    y = rest_hr[:n]
    X = sm.add_constant(x)

    # --- OLS via statsmodels (the convenience route) ---
    ols = sm.OLS(y, X).fit()

    # --- Full ML via scipy.optimize, JonStats-style ---
    # pars = (beta0, beta1, eta) with sigma^2 = exp(eta)
    def negll(pars):
        b0, b1, eta = pars
        s2 = np.exp(eta)
        mu = b0 + b1 * x
        return 0.5 * np.sum(np.log(2 * np.pi * s2) + (y - mu) ** 2 / s2)

    fit = optimize.minimize(negll, x0=np.array([0.0, 0.0, 0.0]), method="BFGS")

    # Numeric Hessian of the NEGATIVE log-likelihood by central differences
    def num_hessian(f, p, h=1e-4):
        k = len(p)
        H = np.zeros((k, k))
        for i in range(k):
            for j in range(k):
                pp = p.copy(); pp[i] += h; pp[j] += h
                pm = p.copy(); pm[i] += h; pm[j] -= h
                mp = p.copy(); mp[i] -= h; mp[j] += h
                mm = p.copy(); mm[i] -= h; mm[j] -= h
                H[i, j] = (f(pp) - f(pm) - f(mp) + f(mm)) / (4 * h * h)
        return H

    H = num_hessian(negll, fit.x)
    # negll is minimised, so H is the observed information directly
    vcov_ml = np.linalg.inv(H)
    se_ml = np.sqrt(np.diag(vcov_ml))

    sigma2_ml = np.exp(fit.x[2])

    print(f"\n--- n = {n} ---")
    print(f"OLS  coefficients: b0 = {ols.params[0]:.4f}, b1 = {ols.params[1]:.4f}")
    print(f"OLS  std errors:   se(b0) = {ols.bse[0]:.4f}, se(b1) = {ols.bse[1]:.4f}")
    print(f"OLS  sigma-hat (df-corrected): {np.sqrt(ols.mse_resid):.4f}")
    print(f"OLS  vcov(beta):\n{ols.cov_params()}")
    print(f"ML   coefficients: b0 = {fit.x[0]:.4f}, b1 = {fit.x[1]:.4f}")
    print(f"ML   sigma-hat (no df correction): {np.sqrt(sigma2_ml):.4f}")
    print(f"ML   std errors from inverse Hessian: se(b0) = {se_ml[0]:.4f}, "
          f"se(b1) = {se_ml[1]:.4f}, se(eta) = {se_ml[2]:.4f}")
    print(f"ML   vcov(beta) from inverse Hessian:\n{vcov_ml[:2, :2]}")
    print(f"Wald 95% CI b1 (OLS): "
          f"({ols.params[1] - 1.96 * ols.bse[1]:.4f}, {ols.params[1] + 1.96 * ols.bse[1]:.4f})")

    # Analytic profile Hessian at the MLE (sigma^2 fixed at ML estimate):
    # for the LOG-LIKELIHOOD (maximised), H = -X'X / sigma^2
    XtX = X.T @ X
    H_profile = -XtX / sigma2_ml
    print(f"Analytic profile Hessian of ll at peak (sigma^2 fixed at ML):\n{H_profile}")
    print(f"Inverse of negated profile Hessian (= vcov used by the page):\n"
          f"{np.linalg.inv(-H_profile)}")
    return ols


gaussian_report(DEFAULT_N)
gaussian_report(N_FULL)

# ---------------------------------------------------------------
# Binomial demo numbers (bayes.html, beat 1): y successes out of n
# ---------------------------------------------------------------
print("\n" + "=" * 70)
print("BINOMIAL DEMO (bayes.html): y = 2 successes out of n = 20")
print("=" * 70)

y_b, n_b = 2, 20
p_hat = y_b / n_b
se_wald = np.sqrt(p_hat * (1 - p_hat) / n_b)
print(f"p-hat = {p_hat:.4f}, Wald SE = {se_wald:.4f}")
print(f"Wald 95% CI: ({p_hat - 1.96 * se_wald:.4f}, {p_hat + 1.96 * se_wald:.4f})  <-- leaks below 0")
lo, med, hi = stats.beta.ppf([0.025, 0.5, 0.975], y_b + 1, n_b - y_b + 1)
print(f"Flat-prior posterior Beta({y_b + 1}, {n_b - y_b + 1}):")
print(f"  95% credible interval: ({lo:.4f}, {hi:.4f}), median {med:.4f}  <-- stays in (0,1)")

# Grid check (mirrors the JS implementation on the page)
grid = np.linspace(0.0005, 0.9995, 2000)
post = grid ** y_b * (1 - grid) ** (n_b - y_b)
post /= post.sum()
cdf = np.cumsum(post)
g_lo = grid[np.searchsorted(cdf, 0.025)]
g_med = grid[np.searchsorted(cdf, 0.5)]
g_hi = grid[np.searchsorted(cdf, 0.975)]
print(f"Grid-posterior check (2000 points): ({g_lo:.4f}, {g_hi:.4f}), median {g_med:.4f}")

# ---------------------------------------------------------------
# Dataset 2: Logistic — treatment response vs biomarker score, small n
# ---------------------------------------------------------------
print("\n" + "=" * 70)
print("DATASET 2: treatment response ~ biomarker (logistic, n=30), seed 42")
print("=" * 70)

rng2 = np.random.default_rng(42)
N_LOGIT = 30
biomarker = np.round(rng2.uniform(-2, 2, N_LOGIT), 2)
lin = 0.4 + 1.5 * biomarker
p_true = 1 / (1 + np.exp(-lin))
response = (rng2.uniform(size=N_LOGIT) < p_true).astype(int)

logit_data = [{"x": float(x), "y": int(y)} for x, y in zip(biomarker, response)]
with open("../../docs/data/inference-logistic.json", "w") as f:
    json.dump(
        {
            "description": "Synthetic treatment response (0/1) vs standardised biomarker score. "
                           "Generated by scripts/py/generate_inference_data.py, seed 42. "
                           "True values: intercept 0.4, slope 1.5.",
            "n": N_LOGIT,
            "data": logit_data,
        },
        f,
        indent=1,
    )

print(f"responses: {response.sum()} ones / {N_LOGIT}")

Xl = sm.add_constant(biomarker)
logit_fit = sm.Logit(response, Xl).fit(disp=0)
b = logit_fit.params
se = logit_fit.bse
print(f"MLE: b0 = {b[0]:.4f}, b1 = {b[1]:.4f}")
print(f"Wald SEs: se(b0) = {se[0]:.4f}, se(b1) = {se[1]:.4f}")
print(f"Wald 95% CI b0: ({b[0] - 1.96 * se[0]:.4f}, {b[0] + 1.96 * se[0]:.4f})")
print(f"Wald 95% CI b1: ({b[1] - 1.96 * se[1]:.4f}, {b[1] + 1.96 * se[1]:.4f})")
print(f"vcov:\n{logit_fit.cov_params()}")

# Flat-prior grid posterior over (b0, b1) — mirrors the JS implementation:
# grid of 240 x 240 points spanning MLE +/- 6 Wald SEs in each direction.
G = 240
b0_grid = np.linspace(b[0] - 6 * se[0], b[0] + 6 * se[0], G)
b1_grid = np.linspace(b[1] - 6 * se[1], b[1] + 6 * se[1], G)
B0, B1 = np.meshgrid(b0_grid, b1_grid, indexing="ij")

eta = B0[..., None] + B1[..., None] * biomarker[None, None, :]
ll = np.where(response[None, None, :] == 1,
              -np.log1p(np.exp(-eta)),
              -np.log1p(np.exp(eta))).sum(axis=-1)
post2 = np.exp(ll - ll.max())
post2 /= post2.sum()

marg_b0 = post2.sum(axis=1)
marg_b1 = post2.sum(axis=0)


def grid_quantiles(gridvals, weights, qs=(0.025, 0.5, 0.975)):
    cdf = np.cumsum(weights)
    return [float(gridvals[np.searchsorted(cdf, q)]) for q in qs]


q0 = grid_quantiles(b0_grid, marg_b0)
q1 = grid_quantiles(b1_grid, marg_b1)
print(f"Grid posterior (240x240, +/-6 SE, flat prior):")
print(f"  b0: 95% credible interval ({q0[0]:.4f}, {q0[2]:.4f}), median {q0[1]:.4f}")
print(f"  b1: 95% credible interval ({q1[0]:.4f}, {q1[2]:.4f}), median {q1[1]:.4f}")
print(f"  posterior sd b0: {np.sqrt(np.sum(marg_b0 * b0_grid**2) - np.sum(marg_b0 * b0_grid)**2):.4f}")
print(f"  posterior sd b1: {np.sqrt(np.sum(marg_b1 * b1_grid**2) - np.sum(marg_b1 * b1_grid)**2):.4f}")

print("\nDone. JSON files written to docs/data/.")
